services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: computer-algorithms-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_PORT: ${POSTGRE_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRE_PORT}:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: computer-algorithms-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PW}
    volumes:
      - pgadmindata:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: always

  redis:
    image: redis:7.4.2-alpine
    container_name: computer-algorithms-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redisdata:/data
    restart: always

  server:
    image: redis/redisinsight:latest
    container_name: computer-algorithms-redis-insight
    ports:
      - "${REDISINSIGHT_PORT}:${REDISINSIGHT_PORT}"
    restart: always

volumes:
  pgdata:
  pgadmindata:
  redisdata: